knp_paginator:
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
    page_limit: 8 # Nombre d'éléments par page par défaut
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
